### ISSUE TITLE
Making a 2 of 3 multisig account doesn't work

### ISSUE THREAD

**Issue by jabo38** [NemProject/NEMiOSApp#135]
when I try to make a 2 of 3 multisig account a transaction error comes up.  making a 1 of 1 works just fine.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 21

**Comment by LyubomirDominik** [comment]
#226

**Comment by jabo38** [comment]
I just tried to make a 2 of 4 and had the same problem.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 40

**Comment by jabo38** [comment]
fixed
