### ISSUE TITLE
multisig app crashes

### ISSUE THREAD

**Issue by jabo38** [NemProject/NEMiOSApp#161]
Problem 1:  Bad error comes too late. 

I try to add an account that can't be added to multisig because it itself is already multisig.  The app lets me add it and then try to send a transaction, but the transaction gives me a generic error that it didn't go through and to try again later or check server. Neither checking server or trying again later will help.

Ideally it would be nice to not allow that account to be added in the first place, or to be more clear on the error.  

Problem 2: Now said account is in my accounts signers list but wasn't really added and can't be added, so I try to remove it manually by pressing X and then the app crashes.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 30

**Comment by fyahfox** [comment]
@jabo38 please close, if you can confirm this fixed

**Comment by jabo38** [comment]
fixed
