### ISSUE TITLE
Keep on getting "11 new transactions" for one account although no new transactions

### ISSUE THREAD

**Issue by jabo38** [NemProject/NEMiOSApp#192]
One of my accounts keeps on getting an alert for new messages, I go and check it and there is no new messages.

**Comment by LyubomirDominik** [comment]
Need your private key or export account QR

**Comment by Espo02** [comment]
Same on my Iphone. 
The pushmessage says that I have 16 Transaction. 
Today I only did 1 Transaction by the app ...
![photo-2016-04-08-19-08-30_1416](https://cloud.githubusercontent.com/assets/17567386/14392374/5301bfb8-fdc1-11e5-8895-4a96da77c759.PNG)

**Comment by Espo02** [comment]
mobilenem: (Password: nemnem)
![photo-2016-04-08-19-40-02_1417](https://cloud.githubusercontent.com/assets/17567386/14392493/e1cb3e68-fdc1-11e5-9045-0e46e4e53bd1.PNG)

**Comment by jabo38** [comment]
Here is another example.  I have notifications set to every thirty minutes, but all these transactions that are showing as new are actually old.  

![image](https://cloud.githubusercontent.com/assets/10395907/14401906/6a886cd6-fe5c-11e5-8177-3db4fd078217.png)


I'll PM you my key.

**Comment by LyubomirDominik** [comment]
Try to reproduce in Version 2 Build 33. Not sure that it fixed as can not reproduce, but I think that I fix it in right place.

**Comment by Espo02** [comment]
I made 2 transactions with one account and get this message afterwards:
![photo-2016-06-09-10-06-53_2081](https://cloud.githubusercontent.com/assets/17567386/15923220/523dc9aa-2e2c-11e6-814b-78fb276c6696.PNG)

**Comment by fyahfox** [comment]
@Espo02 reported that this is still not fixed. So please look into it again, that is pretty important of course.

**Comment by jabo38** [comment]
I agree

**Comment by LyubomirDominik** [comment]
Can not reproduce in Version 2 Build 39

**Comment by jabo38** [comment]
@Espo02 can you please test with the next version 39?

**Comment by Espo02** [comment]
Version 39Beta:
I made 2 sending transactions and got 2 transactions.
Therefore the push-messages were like spam again.
![photo-2016-06-21-18-51-55_2391](https://cloud.githubusercontent.com/assets/17567386/16242698/f9374904-37f3-11e6-9beb-21c255c2f773.PNG)

Then I made 1 (one) sending transaction to jabo38.
![photo-2016-06-21-19-53-38_2393](https://cloud.githubusercontent.com/assets/17567386/16242720/1c807994-37f4-11e6-904c-aa32a320f254.PNG)
And it shows 14. I don't have any Idea where the 14 come from...

**Comment by fyahfox** [comment]
(not sure what the "help wanted" label was for, please explain if you still think that label is needed here.)

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 40

**Comment by Espo02** [comment]
For the last few incomming transactions it worked for me.
I will make a few tests on the next days :)

![photo-2016-07-12-22-36-29_2777](https://cloud.githubusercontent.com/assets/17567386/16784152/b663defe-4887-11e6-8740-ceb7996b0010.PNG)

**Comment by jabo38** [comment]
fixed
