### ISSUE TITLE
small cosmetics: add spaces in the warning

### ISSUE THREAD

**Issue by Espo02** [NemProject/NEMiOSApp#194]
The warning which reminds you to hold the private key secret needs some spaces. i tested some languages which have all this issue)
![photo-2016-04-08-19-57-12_1420](https://cloud.githubusercontent.com/assets/17567386/14392990/b14c59ea-fdc4-11e5-9552-09f456c400cb.PNG)

**Comment by fyahfox** [comment]
I'll fix that via the translation strings.

**Comment by Espo02** [comment]
The difference Android iOS

![screenshot_20160809-143012](https://cloud.githubusercontent.com/assets/17567386/17516641/ff01aac4-5e3f-11e6-85b8-324280e53bf9.png)

![photo-2016-08-09-14-29-07_3020](https://cloud.githubusercontent.com/assets/17567386/17516664/2204ece8-5e40-11e6-99b6-3bb4e1d4b60b.PNG)

**Comment by fyahfox** [comment]
Does that problem still exist? In our translation table, it is correct.

**Comment by Espo02** [comment]
No, the Problem is solved.
![photo-2016-11-15-07-22-35_3932](https://cloud.githubusercontent.com/assets/17567386/20295305/71de72d2-ab04-11e6-983b-1f5f6319f5a3.PNG)
