### ISSUE TITLE
Add Additional Signer -> where is my mistake?

### ISSUE THREAD

**Issue by Espo02** [NemProject/NEMiOSApp#214]
I wanted to create a Multisig address. 
1. I creadet a new adrress [01Master].
2. Then I sent 3000XEM to [01Master] and waited until it confirmed.
3. I created a new address [01Slave] (the cosigner) and sent 2000XEM.
4. I went to [01Master]->More->Multisig->Add Additional Signer.
5. Copy and pasted an Address [01Slave] from my Computer.
5. I got an Error

Espo: NDEFC3-H4VAIU-FQ5GFT-IK3IJR-4DGKF7-PEQKRW-LPZ5

![photo-2016-05-29-14-28-52_1966](https://cloud.githubusercontent.com/assets/17567386/15633345/0595a75a-25ab-11e6-8523-b7d5d9a2c8f5.PNG)

**Comment by Espo02** [comment]
Ok, to create a new Multisigaccount on a mobile device is maybe difficult. But to add an existing Account as a cosigner to an existing Multisig account should work.

![photo-2016-05-29-15-01-38_1967](https://cloud.githubusercontent.com/assets/17567386/15633519/b7c65f66-25ae-11e6-969a-d1b8c0b9da3a.PNG)

**Comment by jabo38** [comment]
you didn't do anything wrong.  right now it seems the app can only support public keys

**Comment by jabo38** [comment]
Need to update strings

**Comment by Espo02** [comment]
If you try to add now an Account(BETA38) the app crashes.
(Multisig account A, Cosigner 1 and 2; 2 wants to add signer 3 with the NEMapp)
