### ISSUE TITLE
It shouldn't be possible to add the same account more than once

### ISSUE THREAD

**Issue by thomasoehri** [NemProject/NEMiOSApp#219]
If you import an existing account via QR-Code and then try to import the account a second time via QR-Code an error message gets displayed - this is how it should be. If we add an existing account via QR-Code and then add the existing account a second time via import of the private key no error message gets displayed and the account gets added a second time. In this case there should also be an error message informing the user that the account already got added.

NDXRV4-767UOX-C2CY3Y-IRLFMB-TWIXXS-V7GQYO-WELC

**Comment by Mehbsl** [comment]
Ok, i just noticed that sometimes an error message gets displayed. Just sometimes it is as if the application has forgotten that an account with the same private key already exists.

**Proof that it's possible:**

![img_2285 png](https://cloud.githubusercontent.com/assets/18571472/15650155/e3ce065e-2676-11e6-8d90-eda7ea7af64f.jpeg)
![img_2286 png](https://cloud.githubusercontent.com/assets/18571472/15650157/e41c1574-2676-11e6-966c-3dfaa3ec172a.jpeg)
![img_2287 png](https://cloud.githubusercontent.com/assets/18571472/15650156/e41a815a-2676-11e6-891e-662bab5b1232.jpeg)

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 39

**Comment by Mehbsl** [comment]
I'm not able to test if this issue is resolved due to issue #242

**Comment by Mehbsl** [comment]
Okay - this is now fixed for "normal" accounts, but with testnet account 17 & 18 you're able to add the same account as many times as you want via QR code.

**Comment by jabo38** [comment]
Not fixed.  I was able to add #22 many times

**Comment by jabo38** [comment]
![image](https://cloud.githubusercontent.com/assets/10395907/16219067/723c63f6-37be-11e6-96f5-20106650a259.png)


![image](https://cloud.githubusercontent.com/assets/10395907/16219075/83c1c4a4-37be-11e6-9187-df26ec28785a.png)

**Comment by jabo38** [comment]
Import password is: 20172017

**Comment by thomasoehri** [comment]
Resolved for me with version 2 build 40

**Comment by jabo38** [comment]
resolved

**Comment by jabo38** [comment]
Bounty paid. Tx hash: 7c264cf6ba7cb3396cdb431cbcba7f797862d630439ffce25ee7ef4aa8b767a2
