### ISSUE TITLE
Serious Issues regarding Memory Management

### ISSUE THREAD

**Issue by thomasoehri** [NemProject/NEMiOSApp#221]
I just ran some tests regarding memory management and noticed that view controllers (and the data stored with them) don't get deinitialized / deallocated. 

Example: You open the dashboard page for an account, close it and open it again -> A dashboard view controller gets initialized (& all transactions get loaded from the API), when you close the dashboard page the view controller doesn't get deallocated (the view controller including all data like transactions that were loaded remain in memory). Now you open the dashboard for the account again and another view controller gets initialized (all transactions again get loaded from the API inside the new view controller). 

If you don't completely close the application all these once used view controllers remain in memory, which ultimately leads to a crash of not only the NEM application, but possibly also other open applications on the phone. **This behavior is very dangerous.**

I opened and closed the dashboard for an account 7 times in the following picture - as you can see the "DashboardVC" is persistent seven times! This behavior isn't limited to the overview page, but also affects all other parts of the application.

![fullsizerender-1](https://cloud.githubusercontent.com/assets/18571472/15651840/538efaba-2682-11e6-8e34-53870195e8b2.jpg)

(sorry for the picture, i somehow couldn't take a screenshot at the moment, but you get the point)

NDXRV4-767UOX-C2CY3Y-IRLFMB-TWIXXS-V7GQYO-WELC

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 40

**Comment by LyubomirDominik** [comment]
![screen shot 2016-07-07 at 16 52 18 2](https://cloud.githubusercontent.com/assets/15227694/16655530/6036580e-4463-11e6-9969-30ac0172e9a6.png)

**Comment by thomasoehri** [comment]
This issue is now fixed in build 40 👍

**Comment by jabo38** [comment]
fixed

**Comment by jabo38** [comment]
Bounty paid. Tx hash: 963a58e235fe84fdc11342d6a0ef6e0e688ed0a469ed12ccbb09c9464e228cd9
