### ISSUE TITLE
making a multisig transaction, clicking "next" crashes app

### ISSUE THREAD

**Issue by jabo38** [NemProject/NEMiOSApp#225]
if I make a new account and send XEM to it.  then I try to turn it into a multisig account and try to adjust the number of signers and click "next" the app will crash every time.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 39

**Comment by Mehbsl** [comment]
Still doesn't work for me, the app crashes.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 40

**Comment by jabo38** [comment]
fixed
