### ISSUE TITLE
making 2 of 5 multisig account produces error

### ISSUE THREAD

**Issue by jabo38** [NemProject/NEMiOSApp#226]
making a 2 of 2 account is fine but when I add a lot of address, like a 2 of 5, I get the following error.  

![image](https://cloud.githubusercontent.com/assets/10395907/15985413/2eb5f8ca-3027-11e6-9f32-a579b4a79112.png)

**Comment by jabo38** [comment]
same issue as here. https://github.com/NewEconomyMovement/NEMiOSApp/issues/135

**Comment by LyubomirDominik** [comment]
![img_3542](https://cloud.githubusercontent.com/assets/15227694/16004552/e79a9dac-316a-11e6-995a-8d455f63d1ca.PNG)
![img_3544](https://cloud.githubusercontent.com/assets/15227694/16004555/e79cc49c-316a-11e6-8454-e35e1481d45e.PNG)
![img_3546](https://cloud.githubusercontent.com/assets/15227694/16004553/e79abb7a-316a-11e6-96bc-1996ec1e939f.PNG)
![img_3547](https://cloud.githubusercontent.com/assets/15227694/16004554/e79b8294-316a-11e6-909a-3901f9294ab0.PNG)

**Comment by LyubomirDominik** [comment]
Can not reproduce in Version 2 Build 39

**Comment by jabo38** [comment]
still not fixed

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 40

**Comment by jabo38** [comment]
it is fixed but there is a lot of confusion.  purely entering only the public keys works.  
sometimes auto-suggest works, sometimes it makes the app crash.  this is discussed here. https://github.com/NemProject/NEMiOSApp/issues/228#issuecomment-233099484 

so I'll close this issue.
