### ISSUE TITLE
Adding more than one signer at a time on multisig won't work

### ISSUE THREAD

**Issue by jabo38** [NemProject/NEMiOSApp#228]
I can add one signer in a multisig edit, but if I try to add more than that, it won't work.  I should be able to go from 3 signers on a multisig transaction to 6 no problem.

**Comment by Mehbsl** [comment]
I'm not even able to add one signer - see #230.

**Comment by jabo38** [comment]
I can add one, sometimes two, but when I try to add many it doesn't work.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 40

**Comment by jabo38** [comment]
I can add more than one, but only if I manually copy and paste in the public key.  If I try to use the autosuggest feature, even for the exact same accounts, even if they are known in the address book and are different apps in my account, the app won't work.

**Comment by LyubomirDominik** [comment]
Remove accounts from address book and reinstall app. And try again.
Account is broken, they was created in old versions or manually

**Comment by jabo38** [comment]
fixed
