### ISSUE TITLE
Create new Invoice -> please make it scrolable

### ISSUE THREAD

**Issue by Espo02** [NemProject/NEMiOSApp#236]
Create new Invoice -> please make it scrolable

![photo-2016-06-11-21-46-08_2195](https://cloud.githubusercontent.com/assets/17567386/15987142/37490dfa-301e-11e6-874f-ae0ec9a6aeb7.PNG)
Espo: NDEFC3-H4VAIU-FQ5GFT-IK3IJR-4DGKF7-PEQKRW-LPZ5

**Comment by Espo02** [comment]
The Keyboard is over the "create" Button. It would help to slide scroll the popup.
Or what did you mean with "question" :)

**Comment by LyubomirDominik** [comment]
"Question" mean that K.Miliak need to agree that this is a bug. This screenshot was done on IPhone 4 This screen size is not supported by the specification.

**Comment by Espo02** [comment]
The taken screenshot above is from my Iphone 5S

**Comment by kmiliak** [comment]
Guys, please check last build (41), developer added scroll to the area with inputs. Let us know if this solution will work as we choose easiest way. Adding scroll to screen would take much time, as developer will need to add scroll to the whole section (three screens)

**Comment by Espo02** [comment]
This solution is very good. It's just that what I had wished in my first post. :)

**Comment by jabo38** [comment]
fixed

**Comment by jabo38** [comment]
Bounty paid. Tx hash:9a201f16342af550f15866ef80a884f12d27dc0d489240e4c7157f2bab4f62d2
