### ISSUE TITLE
Adding an account via QR code succeeds even if i provide a wrong password

### ISSUE THREAD

**Issue by thomasoehri** [NemProject/NEMiOSApp#242]
So with the newest version of the application (version 2 build 39) importing an account via QR code succeeds when i enter a wrong password (even if i don't provide a password), but obviously using the account afterwards isn't possible.

NDXRV4-767UOX-C2CY3Y-IRLFMB-TWIXXS-V7GQYO-WELC

**Comment by Espo02** [comment]
I could reproduce it. 
It shows the right Name of the Account but a diffrent Account Address.

**Comment by Mehbsl** [comment]
I just realized that only accounts like testnet 17 & 18 are affected by this issue.

**Comment by jabo38** [comment]
I can reproduce this error.  Here is how it works for me.  

1. Choose to scan by QR.  
2. Close app and open any different app
3. Open NEM iOS
4. Scan finger print
5. Scan QR
6. Enter any password

Then an account is added that shouldn't be.

**Comment by LyubomirDominik** [comment]
Cannot reproduce

**Comment by jabo38** [comment]
fixed
