### ISSUE TITLE
It is possible to add a account multitimes

### ISSUE THREAD

**Issue by Espo02** [NemProject/NEMiOSApp#244]
It is still possible to add the same account multitimes by adding it by QR-Code. The Privatekey method says "Account exists ..."[picture one]  But the QR Method does'nt proof it. [picture two]

AND: The scrollbar of the dashboard is not directly on the right side [picture two]. Thats looks ... not good. :-1: 

![photo-2016-06-14-16-43-24_2224](https://cloud.githubusercontent.com/assets/17567386/16047209/7c5ba3c0-324f-11e6-997d-ed4a07def459.PNG)
![photo-2016-06-14-16-38-50_2223](https://cloud.githubusercontent.com/assets/17567386/16047233/9c91bf30-324f-11e6-80a0-3fb830fd0668.PNG)

Espo: NDEFC3-H4VAIU-FQ5GFT-IK3IJR-4DGKF7-PEQKRW-LPZ5

**Comment by Mehbsl** [comment]
See #219

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 40

**Comment by jabo38** [comment]
fixed
