### ISSUE TITLE
Back Button takes much time

### ISSUE THREAD

**Issue by Espo02** [NemProject/NEMiOSApp#245]
Could the Backbutton [picture one] of an account (which takes you to the Dashboard) be activated first bevore all transactions have been loaded? With a small bandwidth, with a lot of transactions it takes more than a few seconds to get back to the Dashboard. 
Now it's like an old TV where the channel change takes to much time :)

![photo-2016-06-14-21-18-20_2228](https://cloud.githubusercontent.com/assets/17567386/16056531/2ec0112e-3276-11e6-9084-8075ba9f1345.PNG)

Espo: NDEFC3-H4VAIU-FQ5GFT-IK3IJR-4DGKF7-PEQKRW-LPZ5

**Comment by jabo38** [comment]
@LyubomirDominik is this an easy thing to fix?

**Comment by jabo38** [comment]
this is really causing a problem if the server is slow so I will click must fix.

**Comment by jabo38** [comment]
Its also not just the back button.  It is also things like new transaction

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 42 downloading transactions not influence any more.

**Comment by jabo38** [comment]
okay thanks

**Comment by jabo38** [comment]
Bounty paid. Tx hash: 1d130338b5d90eddda1658243b0f11a1679a4064f90f31d9896a169e412103bb
