### ISSUE TITLE
The "XEM" Unit is only half

### ISSUE THREAD

**Issue by Espo02** [NemProject/NEMiOSApp#247]
The Unit Symbol needs more space if you use all 6 "cent characters.
![photo-2016-06-15-08-31-39_2231](https://cloud.githubusercontent.com/assets/17567386/16070304/b0d19f80-32d4-11e6-931d-2060204dab62.PNG)

Espo: NDEFC3-H4VAIU-FQ5GFT-IK3IJR-4DGKF7-PEQKRW-LPZ5

**Comment by jabo38** [comment]
confirmed.  I don't get the M in XEM on long transaction numbers too.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 40
![screen shot 2016-07-06 at 11 56 05](https://cloud.githubusercontent.com/assets/15227694/16612670/d2f43008-4370-11e6-8030-d126677b57e7.png)

**Comment by jabo38** [comment]
fixed

**Comment by jabo38** [comment]
Bounty paid. Tx hash:eb8a03630c5f43c0e0bc44e71e95e01d00266a60c222801c1c2aab1e6c38ba31
