### ISSUE TITLE
Encrypted transaction without a message will denied

### ISSUE THREAD

**Issue by Espo02** [NemProject/NEMiOSApp#251]
The Button "ENC" has to be deactivated if there will no message filled in. 
And another wired bug (shown on pictures)

1. I want to send Xem from the "nemapptest" account to "von-mixmaster" account (not "mixmaster"). This is just an rebooking. This [von-mixmaster] Account is in the nemApp, too.
![photo-2016-07-12-22-59-42_2780](https://cloud.githubusercontent.com/assets/17567386/16783883/7758d3e6-4886-11e6-9097-409b05c17ed8.PNG)

2. From is right.
To is the "von-mixmaster" account as destination
The Message is empty but I can encrypt.
![photo-2016-07-12-23-00-06_2781](https://cloud.githubusercontent.com/assets/17567386/16783915/a28abd22-4886-11e6-810b-0138b5ceb0df.PNG)

3. I got an error (Because of the empty encrypted message: with message it works or without encrypted it works, too)
BUUUUT: The **From** has changed to the Lable of the **Destination** Address. Why?
![photo-2016-07-12-23-00-15_2782](https://cloud.githubusercontent.com/assets/17567386/16783990/f5718c96-4886-11e6-89c0-ef701b8cd450.PNG)

Espo: NDEFC3-H4VAIU-FQ5GFT-IK3IJR-4DGKF7-PEQKRW-LPZ5

**Comment by Espo02** [comment]
How to reproduce:
Step 1: You have one account with XEM (The Source). Then you create a second one (I call it destination) in the NEMiOSApp and copy the address.
Step 2: Go to the account with xem and make a new transaction to the new account (destination).
Step 2a: sent 300 Xem and wait a while 
Step 3: Sent 20 Xem from Destination to the source back. -> Insert the Address of the source by copy and paste. Send 20 Xem. Empty Encrypted Message. 

What you get: An Error/Info Message where your transaction is denied and the "From" Address changed to the Destination Addresslable.

**Comment by jabo38** [comment]
wow, correct.  I followed the steps and reproduced error.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 41

**Comment by Espo02** [comment]
Hey :) its only half solved. On the "next transaction" screen the issue exists.
![photo-2016-07-20-18-52-54_2886](https://cloud.githubusercontent.com/assets/17567386/16995461/d9ca73dc-4eac-11e6-8e2f-1f5461a60659.PNG)

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 42

**Comment by jabo38** [comment]
fixed

**Comment by jabo38** [comment]
Bounty paid. Tx hash: 30c6d162922a4b8d8ed380b58aeb29df37a9c9cbe29b0fe1507520b3aee74772
