### ISSUE TITLE
False XEM Adress Copy

### ISSUE THREAD

**Issue by kenscho** [NemProject/NEMiOSApp#252]
When you copy via XEM App your XEM Adress the adress is copied without "-"

see Screenshot
![img_2671](https://cloud.githubusercontent.com/assets/13498551/16798367/03ce55c0-48ec-11e6-8834-a772d04c9816.PNG)
![img_2670](https://cloud.githubusercontent.com/assets/13498551/16798413/307f6492-48ec-11e6-8fca-19f5c7f34b2a.PNG)

**Comment by jabo38** [comment]
generally speaking address work with or without dashes, so this won't effect transactions or functionality, but it would be nice to stick to the same format so I agree.
