### ISSUE TITLE
Trying to remove signers from multisig account won't work

### ISSUE THREAD

**Issue by jabo38** [NemProject/NEMiOSApp#253]
I keep on trying to remove signers from a multisig account and get the error "Failure Multisig Not a Cosigner"  

There are two problems with this.  One, it seems like the string is not in English but instead in Debug. That is the lesser problem, the bigger problem is that it isn't removing the signer that it clear shows is a signer.

**Comment by jabo38** [comment]
![photo_2016-07-14_23-26-22](https://cloud.githubusercontent.com/assets/10395907/16863632/760bbcca-4a1a-11e6-8054-2af41b68af6f.jpg)

**Comment by LyubomirDominik** [comment]
Also can not reproduce, could you give me your account to try? 
I think that is not IOS issue

**Comment by jabo38** [comment]
it seems to be working in this release so I will close it.
