### ISSUE TITLE
Add additional signer: keyboard won't dismiss

### ISSUE THREAD

**Issue by thomasoehri** [NemProject/NEMiOSApp#255]
When I plan on adding an additional signer and the keyboard pops up it won't dismiss if i decide against adding a signer and go back via the back button. The keyboard will persist until another text field gets tapped.

Video: https://youtu.be/YQprd-pnfC4

NDXRV4-767UOX-C2CY3Y-IRLFMB-TWIXXS-V7GQYO-WELC

**Comment by LyubomirDominik** [comment]
Can not reproduce in Version 2 Build 40

**Comment by jabo38** [comment]
![photo_2016-07-25_15-32-20](https://cloud.githubusercontent.com/assets/10395907/17116342/fe853882-527c-11e6-83c3-3790db1a874a.jpg)

Reproduced.  

1) go to multisig edit
2) click add additional signer
3) tap to box to add public key and keyboard comes up
4) hit back button

App goes back, screen stays up.

**Comment by LyubomirDominik** [comment]
Fixed Version 2 Build 42. Try to reproduce, I try a lot and could reproduce only ones and hope that I fix it

**Comment by jabo38** [comment]
It is still there.  Not sure why.

**Comment by jabo38** [comment]
fixed

**Comment by jabo38** [comment]
Bounty Paid Transaction hash: 18d767fd13faaad6c6f23f2fc352b8e04f70178bc7392e42cf41d573dae37634
