### ISSUE TITLE
exiting app during entering password for import account and then entering app no touch ID prompt

### ISSUE THREAD

**Issue by jabo38** [NemProject/NEMiOSApp#256]
everytime I leave the app and come back in, I am prompted to use touch ID, but if I leave the app while entering a password for adding an account, then I can open the app with no touch ID prompt, I can then navigate through the app and send transactions as I want.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 4

**Comment by jabo38** [comment]
fixed
