### ISSUE TITLE
new accounts not getting auto-suggest in new transaction

### ISSUE THREAD

**Issue by jabo38** [NemProject/NEMiOSApp#257]
I made a bunch of accounts and went to make a transaction and start to type their name.  No auto-suggestion.  I then added them all to the address book and went to new transaction and typed their name and still no auto-suggest.  

account names were a, b, c, d, e.  all small letters, all one letter names.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 41

**Comment by jabo38** [comment]
fixed

- [ ]
