### ISSUE TITLE
Accounts go out of order on the Accounts List panel

### ISSUE THREAD

**Issue by jabo38** [NemProject/NEMiOSApp#259]
Step 1:  I make lots of accounts.  

![photo_2016-07-25_15-52-10](https://cloud.githubusercontent.com/assets/10395907/17116977/c4a9096a-527f-11e6-904e-ab11d2c14e1e.jpg)

Step 2:  I delete account "e"
![photo_2016-07-25_15-52-54](https://cloud.githubusercontent.com/assets/10395907/17117009/dd19c4f8-527f-11e6-9ca0-8e859a7733e9.jpg)

Step 3:  I kill the app.  

Step 4:  Do a fresh restart of the app and now my accounts are out of order.  

![photo_2016-07-25_15-53-57](https://cloud.githubusercontent.com/assets/10395907/17117049/02e4893e-5280-11e6-85db-6739318f8fc0.jpg)

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 42

**Comment by jabo38** [comment]
fixed
