### ISSUE TITLE
Enhancement: show Transaction Details.

### ISSUE THREAD

**Issue by Espo02** [NemProject/NEMiOSApp#261]
It would be usefull if the App shows the Transaction Details like the page of the hrvesting details. The Infos could be shown on an extra Page if the User tabs on an Transaction

![photo-2016-08-01-21-50-44_2963](https://cloud.githubusercontent.com/assets/17567386/17306950/e9126612-5832-11e6-845a-27b6e895892e.PNG)

**Comment by fyahfox** [comment]
Its already there, you just have to slide the TX to the side :)
