### ISSUE TITLE
Sending below 0.abcdefg message *FEE* ?

### ISSUE THREAD

**Issue by n3lz0n** [NemProject/NEMiOSApp#263]
See example below
http://puu.sh/qpj0K/bd124981c7.png

NEM Wallet:
NCQHY2-SOLUIZ-YLWKW4-SY3DJF-2KZFRP-6TFHIB-IHGK

**Comment by Espo02** [comment]
please show the fees on your screenshoot.
The app shows the Transactiondetails if you wish from right to left on the specified transaction.

**Comment by n3lz0n** [comment]
![img_5620](https://cloud.githubusercontent.com/assets/7638049/17515307/f50aa878-5e7a-11e6-9968-72ee7aa0cc50.PNG)

**Comment by n3lz0n** [comment]
this one? ^^^

**Comment by Espo02** [comment]
something like this:
![photo-2016-08-09-14-17-03_3019](https://cloud.githubusercontent.com/assets/17567386/17516005/382848de-5e3c-11e6-8d94-5aca6bc3fb10.PNG)

**Comment by n3lz0n** [comment]
![img_5621 191963](https://cloud.githubusercontent.com/assets/7638049/17516595/b2956520-5e82-11e6-813d-a29ad57a44d0.PNG)

**Comment by n3lz0n** [comment]
that was awesome :)
