### ISSUE TITLE
Encrypted Message doesn't work on "fast send"

### ISSUE THREAD

**Issue by Espo02** [NemProject/NEMiOSApp#272]
First, how ist the screen calling from Picture[1] ?
However, on this screen an encrypted message isn't working.
The same Transaction on the othe program Gui works.
 Picture[1]:
![photo-2016-09-07-11-26-41_3145](https://cloud.githubusercontent.com/assets/17567386/18307005/b6731160-74ee-11e6-9213-e1fc9651b093.PNG)

Picture[2]: 
![photo-2016-09-07-11-27-07_3146](https://cloud.githubusercontent.com/assets/17567386/18307006/b8c3ceb4-74ee-11e6-862d-dc0a2b53008c.PNG)

Espo: NDEFC3-H4VAIU-FQ5GFT-IK3IJR-4DGKF7-PEQKRW-LPZ5

**Comment by Espo02** [comment]
looked solved.

**Comment by jabo38** [comment]
Bounty Paid Transaction hash: 473ec4f0bc413b466ccd59d93f1d79b79899ef19cfa12bd6fb29185f374ecc35
