### ISSUE TITLE
Long Messages are shown cut-off

### ISSUE THREAD

**Issue by Espo02** [NemProject/NEMiOSApp#278]
Iphone 5S, iOS10, NEM-Version 3.0Beta3 

If you send long messages, the Bubbles will cut off if you reopen the details of an account.

When you see the cut-off messages and you are sending a new one, than they will be stretched right.

[1. Cut-Off Messages]
![photo-2016-10-19-12-28-57_3531](https://cloud.githubusercontent.com/assets/17567386/19531469/0b8be4d2-9638-11e6-9a94-5405135d20d0.PNG)

[2. New Message]
![photo-2016-10-19-12-29-24_3532](https://cloud.githubusercontent.com/assets/17567386/19531478/16dfea0e-9638-11e6-8dd7-533b69554de0.PNG)

[3. Now it's normal]
![photo-2016-10-19-12-29-54_3533](https://cloud.githubusercontent.com/assets/17567386/19531489/22b01930-9638-11e6-97ce-c86b9b084311.PNG)

[4. reopen, it's cut-off again]
![photo-2016-10-19-20-03-18_3535](https://cloud.githubusercontent.com/assets/17567386/19531501/34482480-9638-11e6-910b-1f4154bd10cc.PNG)

Espo: NDEFC3-H4VAIU-FQ5GFT-IK3IJR-4DGKF7-PEQKRW-LPZ5

**Comment by Espo02** [comment]
This issue is solved.
![photo-2016-11-15-07-26-54_3935](https://cloud.githubusercontent.com/assets/17567386/20295416/165c76ce-ab05-11e6-9dac-8d3fe2e1c6c1.PNG)

**Comment by jabo38** [comment]
Bounty Paid Transaction hash: 689bb47af0dd86a9662ecc8ba1999c0feecdbddca38533f2216121a19894ab65
