### ISSUE TITLE
I don't see a way to sign as a cosigner.

### ISSUE THREAD

**Issue by logart89** [NemProject/NEMiOSApp#281]
There's no way to sign as a cosigner in the iOS app. They can only initiate transactions from child multi sig account but they can't sign them. Or at least i could never found a way to sign them.

**Comment by logart89** [comment]
Ok, i found that initiated multisignature transactions from nano wallets and be confirmed with the iOS app but transactions initiated with iOS app couldn't be confirmed in the same iOS app?

**Comment by jabo38** [comment]
they should be able to sign
