### ISSUE TITLE
Amount truncated when scanning invoice

### ISSUE THREAD

**Issue by takecian** [NemProject/NEMiOSApp#291]
When scanning QR code which has following invoice, amount truncated to `1.0`. This is to be `1.234567`.
```
{"v":2,"type":2,"data":{"addr":"XXXXXXXXXXXXXXXXXXXXX","amount":1234567,"msg":"invoice","name":"Test%20XEM%20invoice"}}
```

**Comment by jabo38** [comment]
Bounty paid. Tx hash: c21fec9a2721c238f29089dac5443fb06b3d5184b102069eaf6a438c0d62b73e

**Comment by jabo38** [comment]
Bounty paid. Tx hash: c21fec9a2721c238f29089dac5443fb06b3d5184b102069eaf6a438c0d62b73e
