### ISSUE TITLE
Hitting Searchbutton in address book crashes app

### ISSUE THREAD

**Issue by ixidion** [NemProject/NEMiOSApp#297]
When I hit the search button (magnifying glass symbol) in the address book section, the App crashes/closes.
iPhone 6, iOS 10.3.3, language german

NBZ47A-LY5XTV-YTXOVE-RGMGH7-J6UUBU-WCAFTG-5SQP for bounty

**Comment by ixidion** [comment]
Is fixed in current version 1.1.3

**Comment by jabo38** [comment]
Bounty paid. Tx hash: c0ce2937ab1ab8e249bc9716eb0a43e990da41189e3c313634a01b9ceb98771d

**Comment by ixidion** [comment]
Thanks, received. 👍
