### ISSUE TITLE
Send mosaic with the iOS app

### ISSUE THREAD

**Issue by merc1305** [NemProject/NEMiOSApp#313]
Do you believe it's possible? Of may be added to the delivery plans?

**Comment by thomasoehri** [comment]
Yes, adding support for sending and receiving mosaics is a main focus for future versions and is already being worked on.
The feature won't be ready in the near term though.

**Comment by takahser** [comment]
We also need that feature
Within what timeframe can we expect this to be implemented? If you need help let me know
